### ISSUE TITLE
Aren't conflicts possible on "somatic clinical impact" scvs with matching tumor types?

### ISSUE THREAD

**Issue by larrybabb** [ncbi/clinvar#1]
In the documentation you state 

> Conflicts will not be calculated for somatic clinical impact. It is anticipated that it will be common to have multiple classifications for different tumor types and that these should not be considered conflicts. Therefore only the highest tier is reported for the aggregate classification. In addition, on the variant (VCV) web pages, we will show additional information in the aggregate section, including the tumor type or number of tumor types reported for the variant and if there are also SCVs with lower tiers of evidence submitted.

But if two different submitters post different Tiers for the same tumor type, wouldn't that be a conflict? If so, how would this be handled and represented?

**Comment by BaoshanGu** [comment]
Posting for Melissa Landrum:

> Hi Larry,
We are not planning to calculate conflicts for somatic clinical impact based on the feedback we got in user interviews. We heard that it is more important to see the highest tier that was submitted at the summary level, and then all the submitted tiers in the details. They indicated that the simpler approach to aggregation was better.
Once we start to get data submitted in this model, we can see if it would be important to change that. However, I suspect we would only calculate a conflict for submissions that are for the same tumor type and the same assertion type, and for the same drug for therapeutic assertions.
For example, different tiers reported for a therapeutic assertion and a diagnostic assertion for the same tumor type might not be considered conflicts. Or different tiers reported for two therapeutic assertions for different drugs and the same tumor type might not be considered conflicts.
However, different tiers reported for diagnostic assertions for the same tumor type might be considered a conflict. Or different tiers reported for therapeutic assertions for the same drug and tumor type might be considered a conflict.
Thank you for reviewing this documentation, and let us know what other questions you have.
Melissa

**Comment by larrybabb** [comment]
Thank you for the information. Sounds like a very reasonable plan.
